# This is a generated file. Not intended for manual editing.
services:
  identity-api:
    build:
      context: "/Users/seymen/RiderProjects/eShopProject"
      dockerfile: "Microservices/Identity/Identity.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Identity.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "identity.api:dev"
    ports: []
    volumes:
    - "/Users/seymen/RiderProjects/eShopProject/Microservices/Identity/Identity.API:/app:rw"
    - "/Users/seymen/RiderProjects/eShopProject:/src:rw"
    - "/Users/seymen/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
