# This is a generated file. Not intended for manual editing.
services:
  catalog-api:
    build:
      context: "C:\\Users\\seyme\\Desktop\\Projek\\eShopProject"
      dockerfile: "Microservices/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalog.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\seyme\\Desktop\\Projek\\eShopProject\\Microservices\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Users\\seyme\\Desktop\\Projek\\eShopProject:/src:rw"
    - "C:\\Users\\seyme\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
